import { useEffect, useMemo, useState, type ReactNode } from "react";
import { BarChart3, ChevronLeft, Compass, Heart, Library, ListMusic, Menu, MoreHorizontal, Pause, Play, Plus, Search, SkipBack, SkipForward, Sparkles, Volume2, X } from "lucide-react";

type Track={id:string;title:string;artist:string;album:string;cover:string;duration:string;genre:string};
const tracks:Track[]=[
{id:"afterglow",title:"Afterglow",artist:"Nia Sol",album:"Night Drive",cover:"https://images.unsplash.com/photo-1511379938547-c1f69419868d?auto=format&fit=crop&w=900&q=85",duration:"3:42",genre:"Alternative"},
{id:"velvet-sky",title:"Velvet Sky",artist:"Milo Grey",album:"Stillness",cover:"https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=900&q=85",duration:"4:08",genre:"R&B"},
{id:"slow-motion",title:"Slow Motion",artist:"Lena Vale",album:"Tidal",cover:"https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?auto=format&fit=crop&w=900&q=85",duration:"3:51",genre:"Indie"},
{id:"open-water",title:"Open Water",artist:"Kairo",album:"Drift",cover:"https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=900&q=85",duration:"4:16",genre:"Electronic"},
{id:"after-hours",title:"After Hours",artist:"Sora",album:"Blue Room",cover:"https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=900&q=85",duration:"3:28",genre:"Soul"},
{id:"city-lights",title:"City Lights",artist:"Aven",album:"Midnight FM",cover:"https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=900&q=85",duration:"3:57",genre:"Electronic"},
{id:"golden",title:"Golden",artist:"Maya Rue",album:"Sunday",cover:"https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=900&q=85",duration:"3:36",genre:"R&B"},
{id:"echoes",title:"Echoes",artist:"Noah Vale",album:"Rooms",cover:"https://images.unsplash.com/photo-1497032205916-ac775f0649ae?auto=format&fit=crop&w=900&q=85",duration:"4:21",genre:"Indie"}];
const genres=["Afrobeats","R&B","Hip-Hop","Electronic","Indie","Jazz","Alternative"];
const routes=[["Home",Compass],["Search",Search],["Library",Library],["Playlists",ListMusic],["Charts",BarChart3]] as const;

function useRoute(){const[path,setPath]=useState(location.pathname);useEffect(()=>{const f=()=>setPath(location.pathname);addEventListener("popstate",f);return()=>removeEventListener("popstate",f)},[]);const navigate=(to:string)=>{history.pushState({}, "",to);setPath(to);scrollTo({top:0,behavior:"smooth"})};return{path,navigate}}

function App(){
const{path,navigate}=useRoute();const[ current,setCurrent]=useState(tracks[0]);const[playing,setPlaying]=useState(false);const[query,setQuery]=useState("");const[liked,setLiked]=useState<string[]>(()=>JSON.parse(localStorage.getItem("vibra-liked")||"[]"));const[mobile,setMobile]=useState(false);
useEffect(()=>localStorage.setItem("vibra-liked",JSON.stringify(liked)),[liked]);
const filtered=useMemo(()=>tracks.filter(t=>[t.title,t.artist,t.album,t.genre].join(" ").toLowerCase().includes(query.toLowerCase())),[query]);
const play=(t:Track)=>{setCurrent(t);setPlaying(true)};const like=(id:string)=>setLiked(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);const go=(label:string)=>{setMobile(false);navigate(label==="Home"?"/":"/"+label.toLowerCase())};const next=()=>{const i=tracks.findIndex(t=>t.id===current.id);play(tracks[(i+1)%tracks.length])};const prev=()=>{const i=tracks.findIndex(t=>t.id===current.id);play(tracks[(i-1+tracks.length)%tracks.length])};const active=path==="/"?"Home":path.slice(1).split("/")[0].replace("-"," ").replace(/^./,c=>c.toUpperCase());
return <div className="app"><aside className="sidebar"><button className="brand" onClick={()=>go("Home")}><span className="brand-icon">v</span><span>vibra</span></button><nav>{routes.map(([label,Icon])=><button key={label} className={active===label?"nav active":"nav"} onClick={()=>go(label)}><Icon size={18}/><span>{label}</span></button>)}</nav><div className="side-section"><div className="side-label">YOUR MUSIC</div><button className="nav" onClick={()=>go("Library")}><Heart size={18}/><span>Liked songs</span></button><button className="nav" onClick={()=>go("Playlists")}><Plus size={18}/><span>Create playlist</span></button></div><div className="sidebar-foot"><span>VIBRA</span><small>Music, without the noise.</small></div></aside>
<main><header className="topbar"><button className="mobile-menu" onClick={()=>setMobile(!mobile)}><Menu size={20}/></button><div className="searchbar"><Search size={17}/><input value={query} onChange={e=>{setQuery(e.target.value);if(path!=="/search")navigate("/search")}} placeholder="Search music, artists, albums"/>{query&&<button onClick={()=>setQuery("")}><X size={15}/></button>}</div><div className="top-actions"><button className="upgrade">Try Vibra Plus</button><button className="avatar">SN</button></div></header>
{mobile&&<div className="mobile-nav">{routes.map(([label])=><button key={label} onClick={()=>go(label)}>{label}</button>)}</div>}
{path==="/"?<Home current={current} play={play} like={like} liked={liked} navigate={navigate}/>:path.startsWith("/search")?<SearchPage query={query} results={filtered} play={play}/>:path.startsWith("/library")?<LibraryPage tracks={tracks.filter(t=>liked.includes(t.id))} current={current} play={play} like={like} liked={liked}/>:path.startsWith("/playlists")?<EmptyPage icon={<ListMusic/>} title="Your playlists" text="Create a space for every mood, moment or obsession." action="Create playlist"/>:<PageShell eyebrow="Vibra charts" title="Charts"><TrackList tracks={tracks} current={current} play={play} like={like} liked={liked}/></PageShell>}
<div className="player"><div className="now"><img src={current.cover}/><div><strong>{current.title}</strong><span>{current.artist}</span></div><button onClick={()=>like(current.id)} className={liked.includes(current.id)?"liked":""}><Heart size={17} fill={liked.includes(current.id)?"currentColor":"none"}/></button></div><div className="player-center"><div className="player-controls"><button onClick={prev}><SkipBack size={17} fill="currentColor"/></button><button className="main-play" onClick={()=>setPlaying(!playing)}>{playing?<Pause size={18} fill="currentColor"/>:<Play size={18} fill="currentColor"/>}</button><button onClick={next}><SkipForward size={17} fill="currentColor"/></button></div><div className="player-progress"><span className={playing?"running":""}/></div></div><div className="player-right"><span>1:42</span><span>{current.duration}</span><Volume2 size={17}/><div className="volume-line"><i/></div></div></div></main></div>}

function Home({current,play,like,liked,navigate}:{current:Track;play:(t:Track)=>void;like:(id:string)=>void;liked:string[];navigate:(to:string)=>void}){return <div className="content"><section className="welcome"><div className="welcome-copy"><div className="kicker"><Sparkles size={13}/> MADE FOR YOUR MOMENT</div><h1>Find your<br/><span>next favorite.</span></h1><p>A cleaner way to discover music. No clutter. Just records, artists and sounds worth your time.</p><div className="welcome-actions"><button className="primary" onClick={()=>play(tracks[0])}><Play size={16} fill="currentColor"/> Start listening</button><button className="ghost" onClick={()=>navigate("/search")}>Explore music</button></div></div><div className="feature"><img src={current.cover}/><div className="feature-shade"/><div className="feature-meta"><span>FEATURED RECORD</span><strong>{current.album}</strong><small>{current.artist}</small></div><button className="feature-play" onClick={()=>play(current)}><Play size={22} fill="currentColor"/></button></div></section><SectionTitle kicker="Picked for you" title="Made for you" action="See all"/><div className="cards four">{tracks.slice(0,4).map(t=><MusicCard key={t.id} track={t} play={play}/>)}</div><div className="home-grid"><section><SectionTitle kicker="Keep the night going" title="Quick picks"/><TrackList tracks={tracks.slice(4,8)} current={current} play={play} like={like} liked={liked}/></section><section className="browse"><SectionTitle kicker="Explore by sound" title="Genres"/><div className="genre-grid">{genres.map((g,i)=><button key={g} onClick={()=>navigate("/search?genre="+encodeURIComponent(g))}><span>{String(i+1).padStart(2,"0")}</span>{g}<b>↗</b></button>)}</div></section></div></div>}

function MusicCard({track,play}:{track:Track;play:(t:Track)=>void}){return <article className="music-card" onClick={()=>play(track)}><div className="card-cover"><img src={track.cover}/><button><Play size={17} fill="currentColor"/></button></div><strong>{track.album}</strong><span>{track.artist}</span></article>}
function SectionTitle({kicker,title,action}:{kicker:string;title:string;action?:string}){return <div className="section-title"><div><span>{kicker}</span><h2>{title}</h2></div>{action&&<button>{action}</button>}</div>}
function TrackList({tracks,current,play,like,liked}:{tracks:Track[];current:Track;play:(t:Track)=>void;like:(id:string)=>void;liked:string[]}){return <div className="track-list">{tracks.map((t,i)=><div className={current.id===t.id?"track current":"track"} key={t.id} onClick={()=>play(t)}><span className="track-index">{String(i+1).padStart(2,"0")}</span><img src={t.cover}/><div className="track-name"><strong>{t.title}</strong><span>{t.artist}</span></div><span className="track-album">{t.album}</span><span className="track-duration">{t.duration}</span><button onClick={e=>{e.stopPropagation();like(t.id)}} className={liked.includes(t.id)?"liked":""}><Heart size={16} fill={liked.includes(t.id)?"currentColor":"none"}/></button><MoreHorizontal size={17}/></div>)}</div>}
function PageShell({title,eyebrow,children}:{title:string;eyebrow:string;children:ReactNode}){return <div className="content page-shell"><button className="back" onClick={()=>history.back()}><ChevronLeft size={16}/> Back</button><span className="kicker">{eyebrow}</span><h1>{title}</h1>{children}</div>}
function SearchPage({query,results,play}:{query:string;results:Track[];play:(t:Track)=>void}){return <PageShell eyebrow="Search" title={query?"Results for “"+query+"”":"What are you listening for?"}><p className="page-intro">{query?results.length+" matches in Vibra":"Search songs, artists and albums."}</p>{query?<div className="cards four">{results.map(t=><MusicCard key={t.id} track={t} play={play}/>)}</div>:<div className="search-empty"><Search size={30}/><strong>Start with a song, artist or album</strong></div>}</PageShell>}
function LibraryPage({tracks,current,play,like,liked}:{tracks:Track[];current:Track;play:(t:Track)=>void;like:(id:string)=>void;liked:string[]}){return <PageShell eyebrow="Your collection" title="Library"><div className="library-head"><div><strong>{tracks.length}</strong><span>liked tracks</span></div><button>Recently added</button></div>{tracks.length?<TrackList tracks={tracks} current={current} play={play} like={like} liked={liked}/>:<EmptyPage icon={<Heart/>} title="Nothing saved yet" text="Tap the heart on anything you want to come back to."/>}</PageShell>}
function EmptyPage({icon,title,text,action}:{icon:ReactNode;title:string;text:string;action?:string}){return <div className="empty"><div className="empty-icon">{icon}</div><h2>{title}</h2><p>{text}</p>{action&&<button className="primary"><Plus size={16}/>{action}</button>}</div>}
export default App;