import { useEffect, useMemo, useState, type ReactNode } from "react";
import { BarChart3, ChevronLeft, Compass, Heart, Library, ListMusic, Menu, UserRound, Search, Plus, X, Radio, Disc3, Clock3, Globe2, Music2, Play, Volume2 } from "lucide-react";

type Track={id:string;title:string;artist:string;album:string;cover:string;duration:string;genre:string};
const tracks:Track[]=[];
const genres=["Afrobeats","R&B","Hip-Hop","Electronic","Indie","Jazz","Alternative","Soul"];
const routes=[["Home",Compass],["Discover",Disc3],["Search",Search],["Library",Library],["Playlists",ListMusic],["Charts",BarChart3],["You",UserRound]] as const;
function useRoute(){const[path,setPath]=useState(location.pathname+location.search);useEffect(()=>{const f=()=>setPath(location.pathname+location.search);addEventListener("popstate",f);return()=>removeEventListener("popstate",f)},[]);const navigate=(to:string)=>{history.pushState({}, "",to);setPath(to);scrollTo({top:0,behavior:"smooth"})};return{path,navigate}}
function useLocalClock(){const [now,setNow]=useState(()=>new Date());useEffect(()=>{const timer=window.setInterval(()=>setNow(new Date()),30000);return()=>window.clearInterval(timer)},[]);const timezone=Intl.DateTimeFormat().resolvedOptions().timeZone||"Local time";const time=new Intl.DateTimeFormat(undefined,{hour:"2-digit",minute:"2-digit",hour12:false}).format(now);const hour=Number(new Intl.DateTimeFormat("en-GB",{hour:"2-digit",hourCycle:"h23"}).format(now));const greeting=hour<12?"Good morning.":hour<17?"Good afternoon.":"Good evening.";const zone=timezone.split("/").pop()?.replaceAll("_"," ")||timezone;return{time,timezone,zone,greeting}}
function App(){
const{path,navigate}=useRoute();const{time,timezone,zone,greeting}=useLocalClock();
const[query,setQuery]=useState("");const[mobile,setMobile]=useState(false);
const[liked,setLiked]=useState<string[]>(()=>{try{return (JSON.parse(localStorage.getItem("vibra-liked")||"[]") as string[]).filter(id=>tracks.some(t=>t.id===id))}catch{return[]}});
useEffect(()=>localStorage.setItem("vibra-liked",JSON.stringify(liked)),[liked]);
const genre=new URLSearchParams(path.split("?")[1]||"").get("genre")||"";
const filtered=useMemo(()=>tracks.filter(t=>[t.title,t.artist,t.album,t.genre].join(" ").toLowerCase().includes(query.toLowerCase())&&(!genre||t.genre.toLowerCase()===genre.toLowerCase())),[query,genre]);
const go=(label:string)=>{setMobile(false);navigate(label==="Home"?"/":"/"+label.toLowerCase())};
const active=path==="/"?"Home":path.split("?")[0].slice(1).split("/")[0].replace(/^./,c=>c.toUpperCase());
return <div className="app">
<aside className="sidebar"><button className="brand" onClick={()=>go("Home")}><span className="brand-icon">v</span><span>vibra</span></button><nav>{routes.map(([label,Icon])=><button key={label} className={active===label?"nav active":"nav"} onClick={()=>go(label)}><Icon size={18}/><span>{label}</span></button>)}</nav><div className="side-section"><div className="side-label">YOUR MUSIC</div><button className="nav" onClick={()=>go("Library")}><Heart size={18}/><span>Liked songs</span>{liked.length>0&&<b>{liked.length}</b>}</button><button className="nav" onClick={()=>go("Playlists")}><Plus size={18}/><span>Create playlist</span></button></div><div className="side-section compact"><div className="side-label">VIBRA</div><div className="timezone-side"><Globe2 size={14}/><span>{zone}</span><b>{time}</b></div></div><div className="sidebar-foot"><span>VIBRA</span><small>Music, without the noise.</small></div></aside>
<main><header className="topbar"><button className="mobile-menu" onClick={()=>setMobile(!mobile)}><Menu size={20}/></button><button className="back-forward" onClick={()=>history.back()}><ChevronLeft size={17}/></button><div className="searchbar"><Search size={17}/><input value={query} onChange={e=>{setQuery(e.target.value);if(!path.startsWith("/search"))navigate("/search")}} placeholder="Search songs, artists and albums"/>{query&&<button onClick={()=>setQuery("")}><X size={15}/></button>}</div><div className="top-actions"><div className="local-time" title={timezone}><span>{time}</span><small>{zone}</small></div><button className="avatar" onClick={()=>navigate("/you")}>SN</button></div></header>
{mobile&&<div className="mobile-nav">{routes.map(([label])=><button key={label} onClick={()=>go(label)}>{label}</button>)}</div>}
<div className="layout"><div className="main-column">
{path==="/"?<Home greeting={greeting} time={time} zone={zone} timezone={timezone} navigate={navigate}/>:path.startsWith("/discover")?<DiscoverPage navigate={navigate}/>:path.startsWith("/you")?<ProfilePage liked={liked} navigate={navigate} time={time} zone={zone} timezone={timezone}/>:path.startsWith("/search")?<SearchPage query={query} genre={genre} results={filtered}/>:path.startsWith("/library")?<LibraryPage liked={liked}/>:path.startsWith("/playlists")?<PageShell eyebrow="Your collection" title="Playlists"><EmptyPage icon={<ListMusic/>} title="No playlists yet" text="Your playlists will appear here when you create one." action="Create playlist"/></PageShell>:path.startsWith("/charts")?<PageShell eyebrow="Vibra charts" title="Charts"><EmptyPage icon={<BarChart3/>} title="Charts aren't available yet" text="Charts will appear once Vibra is connected to a real music catalogue."/></PageShell>:<PageShell eyebrow="Vibra" title="Not found"><EmptyPage icon={<Music2/>} title="That page isn't here" text="Head back home to keep exploring."/></PageShell>}
</div><aside className="now-panel now-panel-empty"><div className="now-head"><span>NOW PLAYING</span></div><div className="empty-art"><Music2 size={42}/></div><h2>Nothing playing</h2><p>Choose a track from a connected music catalogue and it will appear here.</p><div className="now-lyrics"><span>YOUR LISTENING SPACE</span><p>No demo tracks or fabricated playback. Real music will show here once a provider is connected.</p></div></aside></div>
<div className="player player-empty"><div className="now"><div className="player-empty-art"><Music2 size={19}/></div><div><strong>Nothing playing</strong><span>Choose music to get started</span></div></div><div className="player-center"><div className="player-controls"><button disabled aria-label="Previous track">‹</button><button className="main-play" disabled aria-label="Play"><Play size={16} fill="currentColor"/></button><button disabled aria-label="Next track">›</button></div><div className="player-progress"><span/></div></div><div className="player-right"><Globe2 size={15}/><span title={timezone}>{time} · {zone}</span><Volume2 size={17}/><div className="volume-line"><i/></div></div></div></main></div>}
function Home({greeting,time,zone,timezone,navigate}:{greeting:string;time:string;zone:string;timezone:string;navigate:(to:string)=>void}){return <div className="content"><section className="welcome welcome-empty"><div className="welcome-copy"><div className="kicker"><Disc3 size={13}/> YOUR MUSIC, YOUR MOMENT</div><h1>{greeting}<br/><span>Find your next favorite.</span></h1><p>Discover music, build your collection and keep the songs you love close. Vibra is ready for a real catalogue—no made-up tracks or stock album covers.</p><div className="welcome-actions"><button className="primary" onClick={()=>navigate("/search")}><Search size={16}/> Find music</button><button className="ghost" onClick={()=>navigate("/discover")}>Explore Vibra</button></div><div className="home-local"><Globe2 size={15}/><span>Local time</span><strong>{time}</strong><small>{zone} · {timezone}</small></div></div><div className="feature feature-empty"><div className="feature-empty-mark"><Music2 size={58}/></div><span>YOUR NEXT FAVORITE<br/>IS WAITING TO BE FOUND</span></div></section><SectionTitle kicker="START HERE" title="Find your sound"/><div className="home-shortcuts">{[{title:"Search music",text:"Look for a song, artist or album.",icon:<Search/>,to:"/search"},{title:"Discover",text:"Explore music when the catalogue is connected.",icon:<Disc3/>,to:"/discover"},{title:"Your library",text:"Your saved music and playlists.",icon:<Library/>,to:"/library"}].map(x=><button className="shortcut" key={x.title} onClick={()=>navigate(x.to)}><span>{x.icon}</span><div><strong>{x.title}</strong><small>{x.text}</small></div><b>↗</b></button>)}</div><SectionTitle kicker="BROWSE BY SOUND" title="Genres"/><div className="genre-grid">{genres.map((g,i)=><button key={g} onClick={()=>navigate("/search?genre="+encodeURIComponent(g))}><span>{String(i+1).padStart(2,"0")}</span>{g}<b>↗</b></button>)}</div></div>}
function DiscoverPage({navigate}:{navigate:(to:string)=>void}){return <div className="content page-shell"><span className="kicker">A LITTLE OUT OF THE ORDINARY</span><h1>Discover.</h1><p className="page-intro">Explore genres and find a new direction. Real tracks will appear here when Vibra's music catalogue is connected.</p><div className="discover-empty"><Disc3 size={36}/><h2>Your next discovery starts here.</h2><p>There's no demo catalogue behind these screens. Connect a licensed music source to populate discovery with real artists, releases and playable tracks.</p><button className="primary" onClick={()=>navigate("/search")}><Search size={16}/> Search music</button></div><SectionTitle kicker="EXPLORE A SOUND" title="Browse genres"/><div className="discover-moods">{genres.map((g,i)=><button key={g} onClick={()=>navigate("/search?genre="+encodeURIComponent(g))}><span>0{i+1}</span><b>{g}</b><i>↗</i></button>)}</div></div>}
function ProfilePage({liked,navigate,time,zone,timezone}:{liked:string[];navigate:(to:string)=>void;time:string;zone:string;timezone:string}){return <PageShell eyebrow="Your Vibra" title="Your space."><div className="profile-hero"><div className="profile-large">SN</div><div><span className="kicker">LISTENER PROFILE</span><h2>Your listening space</h2><p>Personal settings and your music collection.</p></div></div><SectionTitle kicker="YOUR LISTENING" title="Your collection"/><div className="profile-stats"><button onClick={()=>navigate("/library")}><Heart/><b>{liked.length}</b><span>Liked tracks</span></button><button onClick={()=>navigate("/playlists")}><ListMusic/><b>—</b><span>Playlists</span></button><button><Clock3/><b>—</b><span>Listening history</span></button></div><div className="profile-note"><h3>Local time & region</h3><p>{time} · {zone}</p><small>{timezone} · Detected from your browser. Vibra doesn't need your precise location.</small></div></PageShell>}
function SearchPage({query,genre,results}:{query:string;genre:string;results:Track[]}){return <PageShell eyebrow="Search" title={genre?genre:query?"Results for “"+query+"”":"What are you listening for?"}><p className="page-intro">{query||genre?results.length+" results":"Search songs, artists and albums."}</p>{results.length?<div className="empty"><h2>Catalogue connection required</h2><p>Connect a real music source to return playable search results.</p></div>:<div className="search-empty"><Search size={30}/><strong>{query||genre?"No matches in the connected catalogue":"Search is ready for a music catalogue"}</strong><p>{query||genre?"No tracks are currently available.":"Vibra isn't showing invented tracks or sample search results."}</p></div>}</PageShell>}
function LibraryPage({liked}:{liked:string[]}){return <PageShell eyebrow="Your collection" title="Library"><div className="library-head"><div><strong>{liked.length}</strong><span>liked tracks</span></div></div><EmptyPage icon={<Heart/>} title={liked.length?"Saved tracks aren't available":"Nothing saved yet"} text={liked.length?"Your previous demo likes were kept locally, but those sample tracks have been removed.":"When you like real tracks from a connected catalogue, they'll be collected here."}/></PageShell>}
function SectionTitle({kicker,title,action}:{kicker:string;title:string;action?:string}){return <div className="section-title"><div><span>{kicker}</span><h2>{title}</h2></div>{action&&<button>{action}</button>}</div>}
function PageShell({title,eyebrow,children}:{title:string;eyebrow:string;children:ReactNode}){return <div className="content page-shell"><button className="back" onClick={()=>history.back()}><ChevronLeft size={16}/> Back</button><span className="kicker">{eyebrow}</span><h1>{title}</h1>{children}</div>}
function EmptyPage({icon,title,text,action}:{icon:ReactNode;title:string;text:string;action?:string}){return <div className="empty"><div className="empty-icon">{icon}</div><h2>{title}</h2><p>{text}</p>{action&&<button className="primary"><Plus size={16}/>{action}</button>}</div>}
export default App;
