import {useEffect,useMemo,useRef,useState,type ReactNode} from "react";
import {BarChart3,ChevronLeft,Compass,Heart,Library,ListMusic,Menu,UserRound,Search,Plus,X,Radio,Disc3,Clock3,Globe2,Music2,Play,Pause,Volume2,SkipBack,SkipForward,Mic2,AlignLeft,ExternalLink,LoaderCircle} from "lucide-react";

type Track={id:string;title:string;artist:string;album:string;cover:string;previewUrl:string;duration:number;genre:string;releaseDate?:string};
const genres=["Afrobeats","R&B","Hip-Hop","Electronic","Indie","Jazz","Alternative","Soul"];
const routes=[["Home",Compass],["Discover",Disc3],["Search",Search],["Library",Library],["Playlists",ListMusic],["Charts",BarChart3],["You",UserRound]] as const;
function fmt(s:number){if(!Number.isFinite(s)||s<0)return "0:00";return Math.floor(s/60)+":"+String(Math.floor(s%60)).padStart(2,"0")}
function useRoute(){const[path,setPath]=useState(location.pathname+location.search);useEffect(()=>{const f=()=>setPath(location.pathname+location.search);addEventListener("popstate",f);return()=>removeEventListener("popstate",f)},[]);const navigate=(to:string)=>{history.pushState({}, "",to);setPath(to);scrollTo({top:0,behavior:"smooth"})};return{path,navigate}}
function useLocalClock(){const[now,setNow]=useState(()=>new Date());useEffect(()=>{const id=window.setInterval(()=>setNow(new Date()),30000);return()=>clearInterval(id)},[]);const timezone=Intl.DateTimeFormat().resolvedOptions().timeZone||"Local time";const time=new Intl.DateTimeFormat(undefined,{hour:"2-digit",minute:"2-digit",hour12:false}).format(now);const hour=Number(new Intl.DateTimeFormat("en-GB",{hour:"2-digit",hourCycle:"h23"}).format(now));return{time,timezone,greeting:hour<12?"Good morning":hour<17?"Good afternoon":"Good evening"}}
async function searchMusic(term:string,signal?:AbortSignal):Promise<Track[]>{if(!term.trim())return[];const url="https://itunes.apple.com/search?term="+encodeURIComponent(term)+"&media=music&entity=song&limit=35";const res=await fetch(url,{signal});if(!res.ok)throw new Error("Music search is temporarily unavailable.");const data=await res.json();return(data.results||[]).filter((x:any)=>x.previewUrl&&x.trackId).map((x:any)=>({id:String(x.trackId),title:x.trackName||"Untitled",artist:x.artistName||"Unknown artist",album:x.collectionName||"Single",cover:(x.artworkUrl100||"").replace("100x100bb","600x600bb"),previewUrl:x.previewUrl,duration:Math.round((x.trackTimeMillis||0)/1000),genre:x.primaryGenreName||"Music",releaseDate:x.releaseDate}))}
function MusicApp(){
const{path,navigate}=useRoute();const{time,timezone,greeting}=useLocalClock();const[query,setQuery]=useState("");const[results,setResults]=useState<Track[]>([]);const[loading,setLoading]=useState(false);const[error,setError]=useState("");const[mobile,setMobile]=useState(false);const[current,setCurrent]=useState<Track|null>(null);const[playing,setPlaying]=useState(false);const[elapsed,setElapsed]=useState(0);const[duration,setDuration]=useState(0);const[volume,setVolume]=useState(0.8);const[audioError,setAudioError]=useState("");const[lyrics,setLyrics]=useState<{synced:string|null;plain:string|null;source:string}|null>(null);const[lyricsLoading,setLyricsLoading]=useState(false);const[lyricsOpen,setLyricsOpen]=useState(false);const[queue,setQueue]=useState<Track[]>([]);const[liked,setLiked]=useState<Track[]>(()=>{try{return JSON.parse(localStorage.getItem("vibra-liked-v2")||"[]")}catch{return[]}});
const audio=useRef<HTMLAudioElement>(null);const request=useRef<AbortController|null>(null);
useEffect(()=>localStorage.setItem("vibra-liked-v2",JSON.stringify(liked)),[liked]);
const go=(label:string)=>{setMobile(false);navigate(label==="Home"?"/":"/"+label.toLowerCase())};
const active=path==="/"?"Home":path.split("?")[0].slice(1).split("/")[0].replace(/^./,c=>c.toUpperCase());
const runSearch=async(term:string)=>{request.current?.abort();const controller=new AbortController();request.current=controller;setLoading(true);setError("");try{const data=await searchMusic(term,controller.signal);setResults(data);if(!data.length)setError("No tracks with playable previews were found. Try another search.");}catch(e:any){if(e.name!=="AbortError")setError("Music search couldn't load. Check your connection and try again.");}finally{if(!controller.signal.aborted)setLoading(false)}};
useEffect(()=>{if(path.startsWith("/search")){const term=new URLSearchParams(path.split("?")[1]||"").get("q")||query;if(term.trim()){setQuery(term);runSearch(term)}else setResults([])}},[path]);
useEffect(()=>{if(path==="/")runSearch("top hits")},[]);
useEffect(()=>{if(!current)return;setLyrics(null);setLyricsLoading(true);const controller=new AbortController();const url="https://lrclib.net/api/get?artist_name="+encodeURIComponent(current.artist)+"&track_name="+encodeURIComponent(current.title)+"&album_name="+encodeURIComponent(current.album)+"&duration="+current.duration;fetch(url,{signal:controller.signal}).then(r=>r.ok?r.json():null).then(d=>{if(d)setLyrics({synced:d.syncedLyrics||null,plain:d.plainLyrics||null,source:"LRCLIB"});else setLyrics(null)}).catch(()=>setLyrics(null)).finally(()=>setLyricsLoading(false));return()=>controller.abort()},[current?.id]);
useEffect(()=>{if(audio.current)audio.current.volume=volume},[volume]);
const playTrack=(track:Track,list?:Track[])=>{if(current?.id===track.id){if(audio.current){audio.current.currentTime=0;audio.current.play().then(()=>setPlaying(true)).catch(()=>setAudioError("This preview could not be played."))}return}setCurrent(track);setElapsed(0);setAudioError("");setPlaying(true);if(list)setQueue(list);else if(!queue.some(t=>t.id===track.id))setQueue(v=>[...v,track]);setLyricsOpen(false)};
useEffect(()=>{if(!current||!audio.current)return;audio.current.src=current.previewUrl;audio.current.load();audio.current.play().then(()=>setPlaying(true)).catch(()=>{setPlaying(false);setAudioError("Preview playback was blocked. Press play to try again.")})},[current?.id]);
const togglePlay=()=>{if(!audio.current||!current)return;if(playing){audio.current.pause();setPlaying(false)}else{audio.current.play().then(()=>{setPlaying(true);setAudioError("")}).catch(()=>setAudioError("This preview couldn't be played. Try another track."))}};
const playNext=()=>{if(!queue.length||!current)return;const i=queue.findIndex(t=>t.id===current.id);playTrack(queue[(i+1)%queue.length],queue)};
const playPrev=()=>{if(!queue.length||!current)return;const i=queue.findIndex(t=>t.id===current.id);if(elapsed>3){audio.current!.currentTime=0;return}playTrack(queue[(i-1+queue.length)%queue.length],queue)};
const toggleLike=(t:Track)=>setLiked(v=>v.some(x=>x.id===t.id)?v.filter(x=>x.id!==t.id):[t,...v]);
const launchSearch=(term:string)=>{setQuery(term);navigate("/search?q="+encodeURIComponent(term));runSearch(term)};
const visibleLyrics=useMemo(()=>{if(!lyrics?.synced)return[];return lyrics.synced.split("\n").map(line=>{const m=line.match(/^\[(\d{2}):(\d{2})(?:\.(\d{2,3}))?\](.*)$/);if(!m)return null;return{at:Number(m[1])*60+Number(m[2])+Number("0."+(m[3]||"0")),text:m[4].trim()}}).filter((x):x is {at:number;text:string}=>!!x&&!!x.text)},[lyrics]);
const activeLine=visibleLyrics.reduce((n,line,i)=>line.at<=elapsed?i:n,-1);
return <div className="app"><audio ref={audio} onTimeUpdate={e=>{setElapsed(e.currentTarget.currentTime);setDuration(e.currentTarget.duration||current?.duration||0)}} onEnded={playNext} onError={()=>{if(current)setAudioError("Preview unavailable for this track.")}}/>
<aside className="sidebar"><button className="brand" onClick={()=>go("Home")}><span className="brand-icon">v</span><span>vibra</span></button><nav>{routes.map(([label,Icon])=><button key={label} className={active===label?"nav active":"nav"} onClick={()=>go(label)}><Icon size={18}/><span>{label}</span></button>)}</nav><div className="side-section"><div className="side-label">YOUR MUSIC</div><button className="nav" onClick={()=>go("Library")}><Heart size={18}/><span>Liked songs</span>{liked.length>0&&<b>{liked.length}</b>}</button><button className="nav" onClick={()=>go("Playlists")}><Plus size={18}/><span>Create playlist</span></button></div><div className="sidebar-foot"><span>YOUR LOCAL TIME</span><strong>{time}</strong><small>{timezone.replaceAll("_"," ")}</small></div></aside>
<main><header className="topbar"><button className="mobile-menu" onClick={()=>setMobile(!mobile)}><Menu size={20}/></button><button className="back-forward" onClick={()=>history.back()}><ChevronLeft size={17}/></button><form className="searchbar" onSubmit={e=>{e.preventDefault();launchSearch(query)}}><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} onFocus={()=>{if(!path.startsWith("/search"))navigate("/search")}} placeholder="Songs, artists, albums…"/>{query&&<button type="button" onClick={()=>{setQuery("");setResults([])}}><X size={15}/></button>}</form><div className="top-actions"><span className="local-time">{time} <small>EAT · {timezone}</small></span><button className="avatar" onClick={()=>navigate("/you")}>SN</button></div></header>{mobile&&<div className="mobile-nav">{routes.map(([label])=><button key={label} onClick={()=>go(label)}>{label}</button>)}</div>}
<div className="layout"><div className="main-column">
{path==="/"?<Home greeting={greeting} time={time} launchSearch={launchSearch} results={results} loading={loading} playTrack={playTrack}/>:path.startsWith("/discover")?<DiscoverPage launchSearch={launchSearch}/>:path.startsWith("/search")?<SearchPage query={query} setQuery={setQuery} results={results} loading={loading} error={error} launchSearch={launchSearch} playTrack={playTrack} current={current} liked={liked} toggleLike={toggleLike}/>:path.startsWith("/library")?<LibraryPage liked={liked} playTrack={playTrack} current={current} toggleLike={toggleLike}/>:path.startsWith("/playlists")?<PageShell eyebrow="YOUR MUSIC" title="Playlists"><EmptyPage icon={<ListMusic/>} title="Your playlists" text="Playlist creation is coming next. Your liked songs are saved in your library."/></PageShell>:path.startsWith("/charts")?<PageShell eyebrow="LISTEN NOW" title="Charts"><DiscoverPage launchSearch={launchSearch}/></PageShell>:path.startsWith("/you")?<ProfilePage liked={liked} navigate={navigate} time={time} timezone={timezone}/>:<Home greeting={greeting} time={time} launchSearch={launchSearch} results={results} loading={loading} playTrack={playTrack}/>}
</div><aside className="now-panel">{current?<><div className="now-head"><span>NOW PLAYING</span><button onClick={()=>setLyricsOpen(!lyricsOpen)} title="Toggle lyrics"><AlignLeft size={17}/></button></div><img className="now-art" src={current.cover} alt={current.album}/><div className="now-title"><div><h2>{current.title}</h2><p>{current.artist}</p></div><button onClick={()=>toggleLike(current)} className={liked.some(t=>t.id===current.id)?"liked":""}><Heart size={20} fill={liked.some(t=>t.id===current.id)?"currentColor":"none"}/></button></div><div className="now-album"><span>ALBUM</span><p>{current.album}</p></div><div className="now-lyrics"><div className="lyrics-head"><span>LYRICS</span><button onClick={()=>setLyricsOpen(!lyricsOpen)}>{lyricsOpen?"Hide":"Show"}</button></div>{lyricsLoading?<p className="muted"><LoaderCircle size={14} className="spin"/> Finding lyrics…</p>:lyrics?.synced?<div className={"lyrics-lines "+(lyricsOpen?"expanded":"")}>{visibleLyrics.slice(Math.max(0,activeLine-1),Math.max(0,activeLine-1)+ (lyricsOpen?50:4)).map((line,i)=><p className={i+Math.max(0,activeLine-1)===activeLine?"lyric-active":""} key={i}>{line.text}</p>)}</div>:lyrics?.plain?<p className={lyricsOpen?"plain-lyrics expanded":"plain-lyrics"}>{lyrics.plain}</p>:<p className="muted">Lyrics aren't available for this track.</p>}</div><button className="artist-link" onClick={()=>launchSearch(current.artist)}><span>More by {current.artist}</span><ExternalLink size={14}/></button></>:<div className="now-empty"><Disc3 size={32}/><h2>Your next track.</h2><p>Search a song or artist. Playable previews and available lyrics will show here.</p><button className="primary" onClick={()=>navigate("/search")}>Find music</button></div>}</aside></div>
<div className="player"><div className="now">{current?<><img src={current.cover} alt=""/><div><strong>{current.title}</strong><span>{current.artist}</span></div><button onClick={()=>toggleLike(current)} className={liked.some(t=>t.id===current.id)?"liked":""}><Heart size={17} fill={liked.some(t=>t.id===current.id)?"currentColor":"none"}/></button></>:<div className="player-empty-art"><Music2 size={19}/></div>}</div><div className="player-center"><div className="player-controls"><button onClick={playPrev} disabled={!current}><SkipBack size={17} fill="currentColor"/></button><button className="main-play" onClick={togglePlay} disabled={!current}>{playing?<Pause size={18} fill="currentColor"/>:<Play size={18} fill="currentColor"/>}</button><button onClick={playNext} disabled={!current}><SkipForward size={17} fill="currentColor"/></button></div><div className="seek-row"><span>{fmt(elapsed)}</span><input aria-label="Seek" type="range" min="0" max={duration||current?.duration||30} value={Math.min(elapsed,duration||current?.duration||30)} onChange={e=>{if(audio.current)audio.current.currentTime=Number(e.target.value)}}/><span>{fmt(duration||current?.duration||0)}</span></div>{audioError&&<small className="audio-error">{audioError}</small>}</div><div className="player-right"><Volume2 size={17}/><input aria-label="Volume" type="range" min="0" max="1" step=".01" value={volume} onChange={e=>setVolume(Number(e.target.value))}/><button onClick={()=>setLyricsOpen(!lyricsOpen)} title="Lyrics"><Mic2 size={17}/></button></div></div></main></div>}
function Home({greeting,time,launchSearch,results,loading,playTrack}:{greeting:string;time:string;launchSearch:(s:string)=>void;results:Track[];loading:boolean;playTrack:(t:Track,list?:Track[])=>void}){return <div className="content home-content"><div className="home-heading"><div><span className="kicker">{time} · YOUR LOCAL TIME</span><h1>{greeting}, Samuel.</h1><p>Find something worth listening to.</p></div><button className="round-action" onClick={()=>launchSearch("afrobeats")}><Search size={18}/></button></div><section className="home-search-callout" onClick={()=>launchSearch("popular music")}><Search size={21}/><div><strong>What do you want to hear?</strong><span>Search any song, artist or album</span></div><span className="enter-hint">SEARCH ↗</span></section><div className="home-genre"><div className="section-title"><div><span>START WITH A SOUND</span><h2>Browse genres</h2></div></div><div className="genre-pills">{genres.map(g=><button key={g} onClick={()=>launchSearch(g)}>{g}<span>↗</span></button>)}</div></div><div className="section-title"><div><span>FROM THE MUSIC CATALOGUE</span><h2>Search and play</h2></div></div><div className="home-discovery-note"><Disc3 size={24}/><div><strong>Millions of tracks, one search away.</strong><p>Search to pull real music results and playable 30-second previews from the iTunes music catalogue. Full-length streaming depends on connecting a licensed streaming provider.</p></div></div><div className="section-title"><div><span>LIVE CATALOGUE RESULTS</span><h2>Popular right now</h2></div></div>{loading?<div className="loading-state"><LoaderCircle className="spin"/> Loading music…</div>:<div className="home-track-grid">{results.slice(0,8).map(t=><button className="home-track-card" key={t.id} onClick={()=>playTrack(t,results)}><img src={t.cover} alt={t.album}/><span><strong>{t.title}</strong><small>{t.artist}</small></span><i><Play size={15} fill="currentColor"/></i></button>)}</div>}</div>}
function DiscoverPage({launchSearch}:{launchSearch:(s:string)=>void}){return <div className="content page-shell"><span className="kicker">FIND YOUR NEXT FAVORITE</span><h1>Discover</h1><p className="page-intro">Pick a sound, search the catalogue and listen to a preview.</p><div className="discover-genre-grid">{genres.map((g,i)=><button key={g} onClick={()=>launchSearch(g)}><span>0{i+1}</span><strong>{g}</strong><b>↗</b></button>)}</div></div>}
function SearchPage({query,setQuery,results,loading,error,launchSearch,playTrack,current,liked,toggleLike}:{query:string;setQuery:(s:string)=>void;results:Track[];loading:boolean;error:string;launchSearch:(s:string)=>void;playTrack:(t:Track,list?:Track[])=>void;current:Track|null;liked:Track[];toggleLike:(t:Track)=>void}){return <div className="content page-shell search-screen"><span className="kicker">MUSIC SEARCH</span><h1>{query?query:"Search"}</h1><form className="search-large" onSubmit={e=>{e.preventDefault();launchSearch(query)}}><Search size={20}/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Track, artist, album…"/><button type="submit">Search</button></form>{loading?<div className="loading-state"><LoaderCircle className="spin"/> Searching the music catalogue…</div>:error?<div className="empty-result"><Search size={25}/><strong>{error}</strong><span>Try a different spelling or artist name.</span></div>:results.length>0?<><div className="results-meta">{results.length} tracks <span>30-second previews · iTunes catalogue</span></div><div className="results-list">{results.map((t,i)=><div className={"result-row "+(current?.id===t.id?"is-playing":"")} key={t.id} onDoubleClick={()=>playTrack(t,results)}><button className="result-play" onClick={()=>playTrack(t,results)}>{current?.id===t.id&&current? <Pause size={16}/>:<Play size={16} fill="currentColor"/>}</button><img src={t.cover} alt={t.album}/><div className="result-main"><strong>{t.title}</strong><span>{t.artist}</span></div><span className="result-album">{t.album}</span><span className="result-duration">{fmt(t.duration)}</span><button className={"result-like "+(liked.some(x=>x.id===t.id)?"liked":"")} onClick={e=>{e.stopPropagation();toggleLike(t)}}><Heart size={17} fill={liked.some(x=>x.id===t.id)?"currentColor":"none"}/></button></div>)}</div></>:<div className="empty-result"><Disc3 size={30}/><strong>Search the music you love.</strong><span>Try an artist, song, album or genre above.</span><div className="quick-searches">{["Burna Boy","SZA","Kendrick Lamar","Tems"].map(s=><button key={s} onClick={()=>launchSearch(s)}>{s}</button>)}</div></div>}</div>}
function LibraryPage({liked,playTrack,current,toggleLike}:{liked:Track[];playTrack:(t:Track[],list?:Track[])=>void;current:Track|null;toggleLike:(t:Track)=>void}){return <div className="content page-shell"><span className="kicker">YOUR MUSIC</span><h1>Library</h1><div className="library-feature"><div className="library-heart"><Heart size={34} fill="currentColor"/></div><div><span>PLAYLIST</span><h2>Liked songs</h2><p>{liked.length} tracks saved on this device</p></div>{liked.length>0&&<button className="primary" onClick={()=>playTrack(liked[0],liked)}><Play size={16} fill="currentColor"/> Play</button>}</div>{liked.length?<div className="results-list">{liked.map(t=><div className={"result-row "+(current?.id===t.id?"is-playing":"")} key={t.id}><button className="result-play" onClick={()=>playTrack(t,liked)}><Play size={16} fill="currentColor"/></button><img src={t.cover} alt=""/><div className="result-main"><strong>{t.title}</strong><span>{t.artist}</span></div><span className="result-album">{t.album}</span><span className="result-duration">{fmt(t.duration)}</span><button className="result-like liked" onClick={()=>toggleLike(t)}><Heart size={17} fill="currentColor"/></button></div>)}</div>:<div className="empty-result"><Heart size={27}/><strong>Songs you love, all in one place.</strong><span>Tap the heart beside any search result to save it here.</span></div>}</div>}
function ProfilePage({liked,navigate,time,timezone}:{liked:Track[];navigate:(to:string)=>void;time:string;timezone:string}){return <PageShell eyebrow="YOUR VIBRA" title="Your space"><div className="profile-hero"><div className="profile-large">SN</div><div><span className="kicker">LISTENER</span><h2>Samuel</h2><p>Your collection lives on this device.</p></div></div><div className="profile-stats"><button onClick={()=>navigate("/library")}><Heart/><b>{liked.length}</b><span>Liked songs</span></button><button><ListMusic/><b>—</b><span>Playlists</span></button><button><Clock3/><b>—</b><span>Listening history</span></button></div><div className="profile-note"><Globe2 size={16}/><span>{time} · {timezone}</span></div></PageShell>}
function SectionTitle({kicker,title}:{kicker:string;title:string}){return <div className="section-title"><div><span>{kicker}</span><h2>{title}</h2></div></div>}
function PageShell({title,eyebrow,children}:{title:string;eyebrow:string;children:ReactNode}){return <div className="content page-shell"><button className="back" onClick={()=>history.back()}><ChevronLeft size={16}/> Back</button><span className="kicker">{eyebrow}</span><h1>{title}</h1>{children}</div>}
function EmptyPage({icon,title,text}:{icon:ReactNode;title:string;text:string}){return <div className="empty"><div className="empty-icon">{icon}</div><h2>{title}</h2><p>{text}</p></div>}
import AuthGate from "./AuthGate";
export default function App(){return <AuthGate><MusicApp/></AuthGate>}
